### ISSUE TITLE
Source of wallet API available?

### ISSUE THREAD

**Issue by michielpost** [CityOfZion/neo-privatenet-docker#23]
I'm trying to setup a local development environment. I have this docker image running and use Neo-Lux (https://github.com/Relfos/neo-lux) to invoke smart contracts deployed on my private docker testnet.

But Neo-Lux also uses web APIs (http://api.wallet.cityofzion.io AND http://testnet-api.wallet.cityofzion.io), so I'd like to setup my own API to talk to my local testnet. Is the source available somewhere?

**Comment by metachris** [comment]
Not sure, but I think you need to integrate it with [neon-wallet-db](https://github.com/CityOfZion/neon-wallet-db).

Join us on [Discord](https://discord.gg/t4sRYBy) and ping @ixje, I think he did that before.

**Comment by metachris** [comment]
Wanted to add: it's fairly easy to interact with neo-privatenet-docker from neo-python. Check out the docs here too https://hub.docker.com/r/metachris/neo-privnet-with-gas/

**Comment by ixje** [comment]
@michielpost, as @metachris pointed out the `testnet-api.wallet.cityofzion.io` is provided by [neon-wallet-db](https://github.com/CityOfZion/neon-wallet-db). I've written [instructions](https://github.com/ixje/neon-wallet-db/blob/master/privnet-install.md) on how to set that up in combination with this docker image. Note that the instructions point to my fork because I [patched](https://github.com/ixje/neon-wallet-db/commits/master) some things to resolve errors and make the setup easier specifically for use with this docker image.

**Comment by michielpost** [comment]
Thanks, that looks useable. Going to give it a try.
