### ISSUE TITLE
Could not find a version that satisfies the requirement neo-boa==0.3.3

### ISSUE THREAD

**Issue by liuqiuy** [CityOfZion/neo-privatenet-docker#35]
While running 

`$ ./docker_build.sh`

I ran into the problem below:

`Collecting neo-boa==0.3.3 (from -r /opt/neo-python/requirements.txt (line 35))`

`Could not find a version that satisfies the requirement neo-boa==0.3.3 (from -r /opt/neo-python/requirements.txt (line 35)) (from versions: 0.1.5, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2) No matching distribution found for neo-boa==0.3.3 (from -r /opt/neo-python/requirements.txt (line 35))`

`The command '/bin/sh -c pip3 install -r /opt/neo-python/requirements.txt' returned a non-zero code: 1`

**Comment by mayajuni** [comment]
Same situation, same error for me. :(

**Comment by metachris** [comment]
Yes, this is because neo-python's new updates are incompatible with the current Docker file.

I'll update it probably today, please simply use the public Docker image in the meantime: https://hub.docker.com/r/cityofzion/neo-privatenet/

If you want to build it yourself, for now you'd have to change the Dockerfile to use an older version of neo-python, eg. the 0.4.x release.

**Comment by i25959341** [comment]
RUN cd /opt/neo-python && git checkout tags/v0.4.10 

this works for dockerfile

**Comment by metachris** [comment]
Fixed with the latest PR.
